// glze/src/core/math/Color/ExtendedGlazeColors.js
import { Color } from './Color.js';
export const ExtendedColors = {
    ...BasicColors,
    aliceBlue: new Color(0xf0f8ff),
    antiqueWhite: new Color(0xfaebd7),
    aqua: new Color(0x00ffff),
    aquamarine: new Color(0x7fffd4),
    azure: new Color(0xf0ffff),
    beige: new Color(0xf5f5dc),
    bisque: new Color(0xffe4c4),
    blanchedAlmond: new Color(0xffebcd),
    blueViolet: new Color(0x8a2be2),
    brown: new Color(0xa52a2a),
    burlyWood: new Color(0xdeb887),
    cadetBlue: new Color(0x5f9ea0),
    chartreuse: new Color(0x7fff00),
    chocolate: new Color(0xd2691e),
    coral: new Color(0xff7f50),
    cornflowerBlue: new Color(0x6495ed),
    crimson: new Color(0xdc143c),
    darkBlue: new Color(0x00008b),
    darkCyan: new Color(0x008b8b),
    darkGoldenRod: new Color(0xb8860b),
    darkGray: new Color(0xa9a9a9),
    darkGreen: new Color(0x006400),
    darkMagenta: new Color(0x8b008b),
    darkOrange: new Color(0xff8c00),
    darkOrchid: new Color(0x9932cc),
    darkRed: new Color(0x8b0000),
    // ...lanjutkan semua CSS named colors
};
